server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeeShop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    baseline-version: 001
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  freemarker:
    expose-request-attributes: true
logging:
  file:
    name: src/main/resources/logs/application-debug.log
  logback:
    rollingpolicy:
      max-file-size: 20MB